<a href="https://colab.research.google.com/github/Sohini3018/MachineLearning/blob/main/Class_2_Continution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.random.randint(10,100,(3,4))
b=np.random.randint(10,100,(7,4))

In [ ]:
a

array([[60, 12, 77, 54],
       [61, 31, 74, 15],
       [66, 61, 52, 33]])

In [ ]:
b

array([[24, 47, 93, 22],
       [13, 55, 56, 15],
       [85, 27, 43, 57],
       [76, 38, 15, 88],
       [75, 17, 75, 51],
       [41, 13, 85, 79],
       [71, 16, 67, 68]])

In [ ]:
c=np.vstack([a,b]) #Vertical Stacking

In [ ]:
c

array([[60, 12, 77, 54],
       [61, 31, 74, 15],
       [66, 61, 52, 33],
       [24, 47, 93, 22],
       [13, 55, 56, 15],
       [85, 27, 43, 57],
       [76, 38, 15, 88],
       [75, 17, 75, 51],
       [41, 13, 85, 79],
       [71, 16, 67, 68]])

In [ ]:
c.shape

(10, 4)

In [ ]:
d=np.r_[a,b]

In [ ]:
d

array([[60, 12, 77, 54],
       [61, 31, 74, 15],
       [66, 61, 52, 33],
       [24, 47, 93, 22],
       [13, 55, 56, 15],
       [85, 27, 43, 57],
       [76, 38, 15, 88],
       [75, 17, 75, 51],
       [41, 13, 85, 79],
       [71, 16, 67, 68]])

In [ ]:
a=np.random.randint(10,100,(3,4))
b=np.random.randint(10,100,(3,5))
c=np.hstack([a,b])

In [ ]:
a

array([[59, 48, 67, 40],
       [31, 80, 48, 42],
       [48, 53, 45, 75]])

In [ ]:
b

array([[44, 76, 32, 73, 23],
       [52, 55, 75, 18, 99],
       [15, 83, 61, 89, 63]])

In [ ]:
c

array([[59, 48, 67, 40, 44, 76, 32, 73, 23],
       [31, 80, 48, 42, 52, 55, 75, 18, 99],
       [48, 53, 45, 75, 15, 83, 61, 89, 63]])

In [ ]:
d=np.c_[a,b]
d

array([[59, 48, 67, 40, 44, 76, 32, 73, 23],
       [31, 80, 48, 42, 52, 55, 75, 18, 99],
       [48, 53, 45, 75, 15, 83, 61, 89, 63]])