<a href="https://colab.research.google.com/github/Sohini3018/MachineLearning/blob/main/Class_2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a= np.random.randint(0,10,(7,5))
a

array([[6, 8, 7, 5, 2],
       [8, 2, 8, 8, 9],
       [5, 0, 8, 9, 9],
       [2, 4, 8, 6, 9],
       [2, 9, 2, 1, 1],
       [3, 8, 3, 2, 6],
       [6, 9, 5, 5, 0]])

In [ ]:
np.sin(a)

array([[-0.2794155 ,  0.98935825,  0.6569866 , -0.95892427,  0.90929743],
       [ 0.98935825,  0.90929743,  0.98935825,  0.98935825,  0.41211849],
       [-0.95892427,  0.        ,  0.98935825,  0.41211849,  0.41211849],
       [ 0.90929743, -0.7568025 ,  0.98935825, -0.2794155 ,  0.41211849],
       [ 0.90929743,  0.41211849,  0.90929743,  0.84147098,  0.84147098],
       [ 0.14112001,  0.98935825,  0.14112001,  0.90929743, -0.2794155 ],
       [-0.2794155 ,  0.41211849, -0.95892427, -0.95892427,  0.        ]])

In [ ]:
def factorial(n):
  return 1 if n==0 else n * factorial(n-1)

In [ ]:
b=np.zeros_like(a)
b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
for i in range(len(a)):
  for j in range(len(a[i])):
    b[i][j]=factorial(a[i][j])

In [ ]:
vec_fact=np.vectorize(factorial)

In [ ]:
vec_fact(a)

array([[   720,  40320,   5040,    120,      2],
       [ 40320,      2,  40320,  40320, 362880],
       [   120,      1,  40320, 362880, 362880],
       [     2,     24,  40320,    720, 362880],
       [     2, 362880,      2,      1,      1],
       [     6,  40320,      6,      2,    720],
       [   720, 362880,    120,    120,      1]])