<a href="https://colab.research.google.com/github/Sohini3018/Show/blob/main/Class_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
a=np.array([12,5,7,13,6,9,15,2,1])

In [4]:
a

array([12,  5,  7, 13,  6,  9, 15,  2,  1])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.dtype

dtype('int64')

In [8]:
a=np.array([12,  5,  7, 13,  6,  9, 15,  2,  1],dtype=np.int32) #Explicitly mentioned size=32 bits  

In [9]:
a.dtype

dtype('int32')

In [11]:
a.shape

(9,)

In [12]:
a.ndim

1

In [13]:
a[[3,1,6,7]] #Special Indexing...we write the indexes of the numbers to be picked up.This can't be done with slicing techmique.

array([13,  5, 15,  2], dtype=int32)

In [20]:
a[(a>=10)]

array([12, 13, 15], dtype=int32)

In [15]:
a>=10

array([ True, False, False,  True, False, False,  True, False, False])

In [17]:
a2 = np.random.randint(10,100,10)  #min,max,no. of numbers...max will be 99 anyway

In [18]:
a2

array([80, 84, 18, 48, 41, 90, 80, 14, 44, 81])

In [19]:
a2[(a2>=30) & (a2<=50)] #numbers greater than 30 and less than 50

array([48, 41, 44])

In [21]:
a2[(a2<30) | (a2>50)] #numbers less than 30 and greater than 50

array([80, 84, 18, 90, 80, 14, 81])

In [22]:
a3 = np.array([12,5,7,13,6])
a4 = np.array([9,15,2,1,4])

In [23]:
a5 = a3+a4 #Vector Addition
a5

array([21, 20,  9, 14, 10])

In [24]:
np.sin(a3)

array([-0.53657292, -0.95892427,  0.6569866 ,  0.42016704, -0.2794155 ])

In [25]:
b = np.array([
    [12,5,7,13],
    [6,9,15,2],
    [1,4,5,7]
])

In [26]:
b.shape

(3, 4)

In [27]:
b.ndim

2